### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by thepwrtank18** [dskrad/mp3chaps#13]
Input file:
```
00:00:00.000 Kaleidoskull
00:02:29.288 [view-monster]
00:03:18.475 Amnesia Was Her Name
00:07:21.270 [hippocampus]
00:08:47.306 The Man in Stripes and Glasses
00:09:40.514 [spooky sounds vol 6]
00:10:26.101 Marketland
00:15:01.355 [x-ray glasses]
00:15:24.820 Gadzooks
00:18:04.214 [prelude to a knife fight]
00:18:19.205 Knife Fight
00:22:36.661 [autofocus]
00:22:58.661 The Only House That's Not On Fire (Yet)
00:27:53.188 [combs]
00:28:13.021 The Ocean
00:31:45.562 [wet hair]
00:32:05.473 The Afternoon
00:34:48.415 [afterafternoon]
00:35:24.694 Spring Heeled Jack
00:37:38.643 [alternate history]
00:38:08.148 Being a Rock Star
00:40:20.148 [like a balloon]
00:40:42:202 Ask for Nothing
00:43:32.629 [disconnect]
00:43:55.925 The Satirist's Love Song
00:45:58.862 [therapy]
00:46:23.574 The Machine
00:50:30.795 [between the frames]
00:51:22.650 Bill Watterson
00:55:10.485 [sleeping]
00:55:35.242 Something Glowing
00:59:44.330 [finale]
01:00:41.057 Sundial
01:04:47.431 Ben Bernanke
01:09:14.078 Modify
01:12:09.648 Nightmare Fuel
01:13:57.038 Hip Hop Cherry Pop
01:15:34.419 123456 Pokemon
01:17:39.192 Toy Food
01:19:48.861 The Wiggles Hate Each Other in Real Life
01:21:44.418 You Got a Toothache
01:23:26.561 320x200
01:25:20.504 Drinky-Bird
01:27:32.718 Strangelet
01:30:01.595 Today's Secret Word
01:31:43.382 Gadzooks (original version)
01:34:53.663 Everyday French
01:39:21.842 While My Keytar Gently Weeps
01:43:35.981 Treasure Map
01:45:15.745 creepy
01:48:37.039 Super Hey Ya (OutKast remix)
```

Output:
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\[redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\mp3chaps.exe\__main__.py", line 7, in <module>
  File "C:\Users\[redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mp3chaps.py", line 81, in main
    add_chapters(tag, args["<filename>"])
  File "C:\Users\[redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mp3chaps.py", line 45, in add_chapters
    chaps = parse_chapters_file(fname)
  File "C:\Users\[redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mp3chaps.py", line 41, in parse_chapters_file
    chaps.append((to_millisecs(time), title))
  File "C:\Users\[redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mp3chaps.py", line 68, in to_millisecs
    h, m, s = [float(x) for x in time.split(":")]
ValueError: too many values to unpack (expected 3)
```

**Comment by rfjaquez** [comment]
The error is caused by invalid data in the input file.
At line #23, there is a ":" instead of a "." in the timecode ("42:202").
00:40:42:202
