### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by juancri** [dskrad/mp3chaps#2]
Hi,

I got this exception when adding chapters to a file:

```
$ python --version
Python 3.6.4

$ mp3chaps -i file.mp3 
Chapters:
Intro
...
Cierre
Traceback (most recent call last):
  File "/usr/bin/mp3chaps", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/mp3chaps.py", line 80, in main
    add_chapters(tag, args["<filename>"])
  File "/usr/lib/python3.6/site-packages/mp3chaps.py", line 64, in add_chapters
    tag.save()
  File "/usr/lib/python3.6/site-packages/eyed3/id3/tag.py", line 825, in save
    self._saveV2Tag(version, encoding, max_padding)
  File "/usr/lib/python3.6/site-packages/eyed3/id3/tag.py", line 1032, in _saveV2Tag
    max_padding)
  File "/usr/lib/python3.6/site-packages/eyed3/id3/tag.py", line 948, in _render
    raw_frame = f.render()
  File "/usr/lib/python3.6/site-packages/eyed3/id3/frames.py", line 1311, in render
    data = self.element_id + b'\x00'
TypeError: must be str, not bytes

```

**Comment by dskrad** [comment]
What are the contents of the chapter file? I am guessing it is choking on unicode.
The code may not properly support unicode (either my script or the eyeD3 module).

**Comment by juancri** [comment]
`test.chapters.txt: UTF-8 Unicode text`

Should it be just ASCII?

**Comment by dskrad** [comment]
I am not sure what the problem is. ID3 tags should support Unicode, but maybe Unicode is not supported in chapter elements, or I did not implement it correctly.
Try using ASCII.

**Comment by cvrn** [comment]
Got the same error message here. Is there any solution?

**Comment by cyroxx** [comment]
I got the same error with a chapters file that is all ASCII: cyroxx/mp3chaps@37f161321e6b61c0237300ea830c21bbe4d6c5d4

Output: https://travis-ci.org/cyroxx/mp3chaps/jobs/495728026

So the problem must lie elsewhere.

**Comment by dskrad** [comment]
@cyroxx : I got an error when I tried it on the `skate.mp3` you have in your test code. Turns out the file is not a valid mp3 file. It is html.

**Comment by dskrad** [comment]
@juancri @cvrn 
My script cannot handle Unicode characters. Please use ASCII for now.
